#include "VertexMaskForgeRecipeInstanceGeneration.h"

#include "VertexMaskForgeInstanceResultStore.h"
#include "VertexMaskForgeMaterialSlotGenerator.h"
#include "VertexMaskForgeRecipeTypes.h"
#include "VertexMaskForgeWorkingMeshTypes.h" // LogVertexMaskForge

namespace
{
	/**
	 * True iff Existing and Candidate represent the SAME generation requirement for a shared InstanceId
	 * -- same GeneratorType, and (only for MaterialSlot, the one type with real, reliable fields to
	 * compare) the same SelectedSlotIndex/bInvert. No serialization/reflection is used; a non-MaterialSlot
	 * GeneratorType match is accepted without deeper comparison since neither side would ever be
	 * generated by this module regardless (both fail identically as unsupported unless an existing store
	 * entry already satisfies the requirement).
	 */
	bool RequirementsAreConsistent(const FVertexMaskForgeMaskInstance& Existing, const FVertexMaskForgeMaskInstance& Candidate)
	{
		if (Existing.GeneratorType != Candidate.GeneratorType)
		{
			return false;
		}

		if (Existing.GeneratorType == EVertexMaskForgeGeneratorType::MaterialSlot)
		{
			const FVertexMaskForgeMaterialSlotParams* ExistingParams = Existing.Params.TryGet<FVertexMaskForgeMaterialSlotParams>();
			const FVertexMaskForgeMaterialSlotParams* CandidateParams = Candidate.Params.TryGet<FVertexMaskForgeMaterialSlotParams>();
			if (!ExistingParams || !CandidateParams)
			{
				// Defensive only -- unreachable given the GeneratorType/Params coherence invariant.
				return false;
			}
			return ExistingParams->SelectedSlotIndex == CandidateParams->SelectedSlotIndex
				&& ExistingParams->bInvert == CandidateParams->bInvert;
		}

		return true;
	}
}

namespace VertexMaskForgeRecipeInstanceGeneration
{
	bool GenerateRequiredInstanceResultsForRecipe(
		const FVertexMaskForgeRecipe& Recipe,
		FVertexMaskForgeWorkingMesh& WorkingMesh,
		const bool bUseSourceTopology,
		const FStaticMeshLODResources* LOD0,
		FVertexMaskForgeRecipeInstanceGenerationOutput& OutResult)
	{
		// --- Phase 1+2: discovery, InstanceId-only deduplication, collision detection ------------------
		// Read-only against Recipe and WorkingMesh.InstanceResults so far -- no generator has run yet.
		TArray<FGuid> RequiredOrder;
		TMap<FGuid, FVertexMaskForgeMaskInstance> RequirementConfig;

		for (const FVertexMaskForgeFillLayer& Layer : Recipe.FillLayers)
		{
			if (!Layer.bEnabled)
			{
				// AUDITED: skipped entirely -- no lookup, no validation, no inspection of this layer's
				// own Mask Instances at all, per the M16-H-established "disabled == absent" contract.
				continue;
			}

			for (const FVertexMaskForgeMaskInstance& Instance : Layer.MaskStack)
			{
				if (!Instance.bEnabled)
				{
					// AUDITED (M16-I.1): a disabled Mask Instance is semantically ABSENT -- skipped
					// before InstanceId validation, before GeneratorType/Params are inspected, before
					// store lookup, before deduplication/collision detection, and before classification.
					// It never establishes or participates in a requirement. If the same InstanceId also
					// has an enabled occurrence elsewhere in the recipe, that enabled occurrence (whether
					// earlier or later in authoring order) is the one that establishes the requirement --
					// this disabled occurrence contributes nothing either way.
					continue;
				}

				if (!Instance.InstanceId.IsValid())
				{
					UE_LOG(LogVertexMaskForge, Warning,
						TEXT("VertexMaskForgeRecipeInstanceGeneration::GenerateRequiredInstanceResultsForRecipe: an enabled Fill Layer's Mask Instance has an invalid InstanceId."));
					return false;
				}

				if (const FVertexMaskForgeMaskInstance* Existing = RequirementConfig.Find(Instance.InstanceId))
				{
					if (!RequirementsAreConsistent(*Existing, Instance))
					{
						UE_LOG(LogVertexMaskForge, Warning,
							TEXT("VertexMaskForgeRecipeInstanceGeneration::GenerateRequiredInstanceResultsForRecipe: InstanceId %s is referenced with divergent GeneratorType/parameters within the same recipe."),
							*Instance.InstanceId.ToString());
						return false;
					}
					// Consistent repeat reference -- same requirement, no new entry, no reordering.
					continue;
				}

				RequirementConfig.Add(Instance.InstanceId, Instance);
				RequiredOrder.Add(Instance.InstanceId);
			}
		}

		if (RequiredOrder.IsEmpty())
		{
			// Empty recipe, only-disabled-layers, or only-empty-Mask-Stacks -- zero requirements, zero
			// lookups, zero generation. WorkingMesh.InstanceResults is not even snapshotted.
			OutResult.NumRequired = 0;
			OutResult.NumReused = 0;
			OutResult.NumGenerated = 0;
			return true;
		}

		// --- Phase 3: classification (still read-only) -------------------------------------------------
		TArray<FGuid> ToGenerate;
		int32 NumReused = 0;

		for (const FGuid& InstanceId : RequiredOrder)
		{
			if (WorkingMesh.InstanceResults.Contains(InstanceId))
			{
				// AUDITED: presence alone proves usability, regardless of which generator produced it --
				// see FVertexMaskForgeInstanceResultStore's own generator-agnostic contract. Never
				// regenerated, never inspected further.
				++NumReused;
				continue;
			}

			const FVertexMaskForgeMaskInstance& Requirement = RequirementConfig[InstanceId];
			if (Requirement.GeneratorType != EVertexMaskForgeGeneratorType::MaterialSlot)
			{
				UE_LOG(LogVertexMaskForge, Warning,
					TEXT("VertexMaskForgeRecipeInstanceGeneration::GenerateRequiredInstanceResultsForRecipe: InstanceId %s requires generator type %d, which is not yet integrated to the result store -- no fallback, no placeholder."),
					*InstanceId.ToString(), static_cast<int32>(Requirement.GeneratorType));
				return false;
			}

			ToGenerate.Add(InstanceId);
		}

		if (ToGenerate.IsEmpty())
		{
			// Every requirement was already satisfied by an existing entry.
			OutResult.NumRequired = RequiredOrder.Num();
			OutResult.NumReused = NumReused;
			OutResult.NumGenerated = 0;
			return true;
		}

		// --- Phase 4: generation, with snapshot/rollback for atomicity ----------------------------------
		// AUDITED: FVertexMaskForgeWorkingMesh cannot be copied (deleted copy ctor/assign) so a staged
		// WorkingMesh duplicate is not possible; FVertexMaskForgeInstanceResultStore CAN be copied safely
		// (see this module's own header doc comment) -- snapshot that instead, generate live against the
		// real WorkingMesh, and restore the snapshot on the first failure.
		const FVertexMaskForgeInstanceResultStore Snapshot = WorkingMesh.InstanceResults;

		for (const FGuid& InstanceId : ToGenerate)
		{
			const FVertexMaskForgeMaskInstance& Requirement = RequirementConfig[InstanceId];
			const bool bGenerated = VertexMaskForgeMaterialSlotGenerator::GenerateMaterialSlotMaskInstanceResult(
				Requirement, WorkingMesh, bUseSourceTopology, LOD0);

			if (!bGenerated)
			{
				UE_LOG(LogVertexMaskForge, Warning,
					TEXT("VertexMaskForgeRecipeInstanceGeneration::GenerateRequiredInstanceResultsForRecipe: generation failed for InstanceId %s -- rolling back, no partial publication."),
					*InstanceId.ToString());
				WorkingMesh.InstanceResults = Snapshot;
				return false;
			}
		}

		// --- Phase 5: success --------------------------------------------------------------------------
		OutResult.NumRequired = RequiredOrder.Num();
		OutResult.NumReused = NumReused;
		OutResult.NumGenerated = ToGenerate.Num();
		return true;
	}
}
