#pragma once

#include "CoreMinimal.h"
#include "Misc/Guid.h"
#include "VertexMaskForgeMaskTypes.h"

/**
 * M16-K.3A: explicit representation of a dynamic layer's Fill content. None is NOT a placeholder or a
 * disabled/zero-opacity trick -- it means "this layer has no content of its own yet" (a brand new layer,
 * or one whose mask has been removed without a Fill set). Black/White are the only two scalar Fill
 * values this checkpoint defines; there is no arbitrary-color Fill and no FVector3f FillValue here --
 * resolving Fill (and the future "mask present, no Fill" / "mask absent, EffectiveMask == 1" cases) into
 * an actual composed value is explicitly deferred to M16-K.3B. Nothing in this enum or in
 * FVertexMaskForgeLayer below is read by any composition/evaluator/bridge code yet.
 */
enum class EVertexMaskForgeLayerFill : uint8
{
	/** No content -- the layer does not contribute. A freshly added layer starts here. */
	None,

	/** Scalar Fill value 0.0, once M16-K.3B resolves it. */
	Black,

	/** Scalar Fill value 1.0, once M16-K.3B resolves it. */
	White,
};

/**
 * M16-K.3A: one entry in the future dynamic layer stack (see FVertexMaskForgeDynamicLayerStack). Pure
 * value data -- no Slate, no generator/mask reference, no cache, no evaluation. LayerId is the only
 * identity; position is never stored here, only implied by this layer's index inside the owning stack's
 * array (see FVertexMaskForgeDynamicLayerStack's own doc comment on why no OrderIndex field exists).
 *
 * All fields are public, mirroring VertexMaskForgePanel::FVertexMaskForgeMaskLayerParams' own
 * fully-public, no-role, structurally-identical-peers convention (VertexMaskForgeMaskTypes.h).
 *
 * M16-K.3A corrective audit: LayerId being a public field is safe specifically because
 * FVertexMaskForgeDynamicLayerStack never exposes a mutable pointer/reference to an element it owns --
 * every public accessor (FindLayerById, GetLayers) is const-only, so external code can only ever read
 * LayerId, never reassign it or replace the whole layer via `*Ptr = OtherLayer` (the implicitly-defined
 * copy-assignment operator would copy every member, private or not, so making LayerId private alone,
 * without also removing mutable element access, would NOT have closed this). A caller building its own,
 * separate FVertexMaskForgeLayer value (e.g. an "expected" value in a test) may of course set any field
 * freely -- that is just constructing ordinary value data, not mutating the stack's own internal state.
 * RenameLayer exists specifically so Name can be changed without any mutable element access being
 * exposed; there is no controller-owned mutation for the other composition fields yet (Fill/BlendMode/
 * Opacity/channels) because nothing in this checkpoint reads or invalidates them -- see
 * FVertexMaskForgeDynamicLayerStack's own doc comment.
 *
 * Selection (which layer a UI/controller currently has active) is deliberately NOT a field here or on
 * the stack -- see FVertexMaskForgeDynamicLayerStack's own doc comment.
 */
struct FVertexMaskForgeLayer
{
	/** Stable identity, assigned once by FVertexMaskForgeDynamicLayerStack::AddLayer via FGuid::NewGuid()
	 *  and never regenerated by any stack operation (rename/move/etc. all preserve it). Never Source, an
	 *  enum, or an index. */
	FGuid LayerId;

	/** User-facing label. FString (not FText) -- this is session/domain data, not localized UI text; the
	 *  future controller/UI layer is responsible for any FText wrapping. Duplicates across layers are
	 *  explicitly allowed (identity is LayerId, never Name) -- see
	 *  FVertexMaskForgeDynamicLayerStackTests.cpp's DuplicateNamesRemainDistinct. Empty string is also
	 *  explicitly allowed; no domain-level naming policy is imposed here. */
	FString Name;

	/** Whether this layer currently contributes to composition. Independent of Fill -- a layer can be
	 *  Enabled with Fill=None (contributes nothing, but for a different reason: absence of content, not
	 *  a deliberate off switch). Composition semantics for the bEnabled/Fill interaction are for M16-K.3B
	 *  to define; this checkpoint only stores the bit. */
	bool bEnabled = true;

	/** See EVertexMaskForgeLayerFill. Defaults to None -- a freshly constructed/added layer is empty and
	 *  neutral, never defaulting to White or relying on Opacity 0 / bEnabled=false as a substitute. */
	EVertexMaskForgeLayerFill Fill = EVertexMaskForgeLayerFill::None;

	/** Reuses the plugin's existing, already-generic EVertexMaskForgeBlendMode (VertexMaskForgeMaskTypes.h)
	 *  -- no new blend-mode enum is introduced here; the seven modes (Copy/Add/Subtract/Multiply/Overlay/
	 *  Screen/Linear) are already layer-agnostic and already the type VertexMaskForgeSequentialEvaluator
	 *  consumes. Default Copy, matching every other per-layer BlendMode default in the codebase. */
	EVertexMaskForgeBlendMode BlendMode = EVertexMaskForgeBlendMode::Copy;

	/** Finite [0, 1] contract (see FVertexMaskForgeDynamicLayerStack::IsValid, which checks both the range
	 *  and finiteness -- NaN/Infinity are rejected, never silently accepted -- but does not clamp on
	 *  write: this field is public, so an out-of-contract value can be constructed directly; it will only
	 *  be caught by an explicit IsValid() call, exactly like every other public-field domain struct in
	 *  this plugin (e.g. FVertexMaskForgeMaskLayerParams::Opacity). No clamping is performed by this
	 *  checkpoint's evaluator, because this checkpoint does not touch the evaluator at all. */
	float Opacity = 1.0f;

	/** Per-layer Channel Filter -- explicit defaults, all channels affected. Mirrors the panel's existing
	 *  global bChannelFilterR/G/B bools (SVertexMaskForgePanel.h), now per-layer instead of per-panel; see
	 *  the M16-K.3R audit's Channel Filter migration plan for how these two are meant to coexist during
	 *  the transition. Alpha is deliberately NOT represented here -- Alpha is not an editable channel
	 *  anywhere in this plugin (see M16-K.3R audit section 22) and this checkpoint does not change that. */
	bool bAffectRed = true;
	bool bAffectGreen = true;
	bool bAffectBlue = true;
};

/**
 * M16-K.4A: the pure, Slate-free CHANNEL-EXCLUSIVITY DECISION behind the Dynamic Layers UI's discreet
 * per-row tint (SVertexMaskForgePanel::GetDynamicLayerChannelTint, the only caller). Deliberately factored
 * out of the panel so it is directly unit-testable without constructing any Slate widget -- the panel-side
 * function is a thin wrapper that resolves a layer by LayerId and maps this enum to the actual
 * presentation FSlateColor/alpha (a UI concern, kept out of this Slate-free header).
 *
 * Exactly one active channel (bAffect* true, the other two false) resolves to that channel's own value;
 * zero, two, or three active channels resolve to Default -- never a combined/blended color. This is pure
 * derivation from the three flags only; it has no knowledge of FVertexMaskForgeLayer, FGuid,
 * FVertexMaskForgeDynamicLayerStack, or any domain identity -- purely a function of (bool, bool, bool).
 *
 * Alpha-channel support does not exist in the layer domain yet (see FVertexMaskForgeLayer's own Channel
 * Filter doc comment) -- this enum has no White/Alpha case. FUTURE DECISION (documented here, not
 * implemented): once an Alpha channel is added to the domain, an Alpha-only layer (R=G=B=false, A=true)
 * should resolve to a white tint, analogous to how exactly-one-of-RGB resolves to that channel's color
 * today; every other combination that includes Alpha alongside any RGB channel should still resolve to
 * Default, exactly like today's RGB-only combinations do.
 */
enum class EVertexMaskForgeDynamicLayerChannelTint : uint8
{
	/** Zero, two, or three of R/G/B active -- the row's normal, untinted appearance. */
	Default,

	/** Exactly R active. */
	Red,

	/** Exactly G active. */
	Green,

	/** Exactly B active. */
	Blue,
};

/** Pure derivation -- see EVertexMaskForgeDynamicLayerChannelTint's own doc comment for the full contract. */
inline EVertexMaskForgeDynamicLayerChannelTint ResolveDynamicLayerChannelTint(const bool bAffectRed, const bool bAffectGreen, const bool bAffectBlue)
{
	const int32 ActiveChannelCount = (bAffectRed ? 1 : 0) + (bAffectGreen ? 1 : 0) + (bAffectBlue ? 1 : 0);
	if (ActiveChannelCount != 1)
	{
		return EVertexMaskForgeDynamicLayerChannelTint::Default;
	}

	if (bAffectRed)
	{
		return EVertexMaskForgeDynamicLayerChannelTint::Red;
	}
	if (bAffectGreen)
	{
		return EVertexMaskForgeDynamicLayerChannelTint::Green;
	}
	// ActiveChannelCount == 1 and both bAffectRed/bAffectGreen are false -- bAffectBlue must be the one.
	return EVertexMaskForgeDynamicLayerChannelTint::Blue;
}

/**
 * M16-K.4B: pure, Slate-free literal color for the three EXCLUSIVE-channel tint kinds only (FLinearColor
 * is a Core, not Slate, type -- no widget/style dependency here). Deliberately does NOT handle
 * EVertexMaskForgeDynamicLayerChannelTint::Default -- the correct default/neutral presentation color is
 * FStyleColors::Panel (a real Slate style color, requiring SlateCore), chosen specifically to reproduce
 * SBorder's pre-M16-K.4A "Border" brush appearance exactly (see SVertexMaskForgePanel::
 * GetDynamicLayerChannelTint's own doc comment for the full root-cause explanation of why the default
 * must be Panel and must NOT be White once the row's BorderImage is "WhiteBrush") -- that substitution
 * happens at the one real call site, not here, so this Slate-free header is never given a reason to
 * depend on SlateCore/Styling. Calling this with Default is a caller error; it returns transparent black
 * defensively rather than crashing, but no real call site should ever do so.
 */
inline FLinearColor GetDynamicLayerChannelTintColor(const EVertexMaskForgeDynamicLayerChannelTint Tint, const float TintAlpha)
{
	switch (Tint)
	{
	case EVertexMaskForgeDynamicLayerChannelTint::Red:
		return FLinearColor(1.0f, 0.0f, 0.0f, TintAlpha);
	case EVertexMaskForgeDynamicLayerChannelTint::Green:
		return FLinearColor(0.0f, 1.0f, 0.0f, TintAlpha);
	case EVertexMaskForgeDynamicLayerChannelTint::Blue:
		return FLinearColor(0.0f, 0.0f, 1.0f, TintAlpha);
	case EVertexMaskForgeDynamicLayerChannelTint::Default:
	default:
		return FLinearColor(0.0f, 0.0f, 0.0f, 0.0f);
	}
}

/** M16-K.4C: identifies which of a Dynamic Layer's three RGB Channel Filter checkboxes was clicked --
 *  used only to parameterize ResolveDynamicLayerChannelToggle below, never stored, never a substitute for
 *  LayerId/FGuid identity. */
enum class EVertexMaskForgeDynamicLayerChannel : uint8
{
	Red,
	Green,
	Blue,
};

/** Pure output of ResolveDynamicLayerChannelToggle -- the final RGB Channel Filter state to apply via
 *  FVertexMaskForgeDynamicLayerStack::SetLayerChannelFilter (a single, already-atomic call.) */
struct FVertexMaskForgeDynamicLayerChannelToggleResult
{
	bool bAffectRed = true;
	bool bAffectGreen = true;
	bool bAffectBlue = true;
};

/**
 * M16-K.4C: pure, Slate-free Channel Solo decision -- Substance-Painter-style Alt-click behavior for a
 * Dynamic Layer's R/G/B Channel Filter checkboxes. Deliberately separate from both Slate (no widget/
 * modifier-key type appears here -- bAltDown is a plain bool the caller already resolved) and from
 * FVertexMaskForgeDynamicLayerStack (this function never touches a layer or a stack; it only computes
 * what SHOULD be applied, via the existing SetLayerChannelFilter call, at the one real call site in
 * SVertexMaskForgePanel::BuildDynamicLayerRow).
 *
 * Contract:
 *   - bAltDown == false (normal click): ClickedChannel is set to bRequestedChecked (the checkbox's own
 *     new state); the other two channels are returned UNCHANGED from bCurrentRed/Green/Blue. Identical
 *     to the pre-M16-K.4C behavior -- multiple channels, or zero channels, remain fully reachable.
 *   - bAltDown == true (Alt-click, "solo"): ClickedChannel is forced to true; the other two are forced to
 *     false -- REGARDLESS of bRequestedChecked. This is the specific rule that makes Alt-clicking an
 *     already-solo channel a no-op rather than a toggle-off: since SCheckBox always requests the OPPOSITE
 *     of its current checked state on click, Alt-clicking a channel that is already the sole active one
 *     would otherwise request bRequestedChecked=false for it -- this function ignores that request
 *     entirely under Alt and forces ClickedChannel to true unconditionally, so the row can never end up
 *     with zero active channels from an Alt-click.
 * Always returns exactly one of the three following shapes: normal-click's "one channel changed, two
 * preserved", or Alt-click's "exactly the clicked channel true, the other two false" -- never a partial
 * or ambiguous state.
 */
inline FVertexMaskForgeDynamicLayerChannelToggleResult ResolveDynamicLayerChannelToggle(
	const bool bCurrentRed, const bool bCurrentGreen, const bool bCurrentBlue,
	const EVertexMaskForgeDynamicLayerChannel ClickedChannel,
	const bool bRequestedChecked,
	const bool bAltDown)
{
	FVertexMaskForgeDynamicLayerChannelToggleResult Result;

	if (bAltDown)
	{
		Result.bAffectRed = (ClickedChannel == EVertexMaskForgeDynamicLayerChannel::Red);
		Result.bAffectGreen = (ClickedChannel == EVertexMaskForgeDynamicLayerChannel::Green);
		Result.bAffectBlue = (ClickedChannel == EVertexMaskForgeDynamicLayerChannel::Blue);
		return Result;
	}

	Result.bAffectRed = bCurrentRed;
	Result.bAffectGreen = bCurrentGreen;
	Result.bAffectBlue = bCurrentBlue;
	switch (ClickedChannel)
	{
	case EVertexMaskForgeDynamicLayerChannel::Red:
		Result.bAffectRed = bRequestedChecked;
		break;
	case EVertexMaskForgeDynamicLayerChannel::Green:
		Result.bAffectGreen = bRequestedChecked;
		break;
	case EVertexMaskForgeDynamicLayerChannel::Blue:
		Result.bAffectBlue = bRequestedChecked;
		break;
	}
	return Result;
}
