#pragma once

#include "CoreMinimal.h"

struct FVertexMaskForgeRecipe;
struct FVertexMaskForgeWorkingMesh;
struct FStaticMeshLODResources;

/**
 * M16-I: coordinates generating every keyed instance result required by exactly one recipe's ENABLED
 * Fill Layers, delegating all actual generation to the M16-E boundary
 * (VertexMaskForgeMaterialSlotGenerator::GenerateMaterialSlotMaskInstanceResult) -- the only generator
 * integrated to the result store so far. This module never evaluates a Mask Stack, never produces an
 * EffectiveMask or Composite, and never calls the M16-F/G (VertexMaskForgeFillLayerResolution) or M16-H
 * (VertexMaskForgeRecipeEvaluation) boundaries -- generation and evaluation remain two separately
 * authorized checkpoints, per this checkpoint's own contract.
 *
 * AUDITED (structural constraint on domain/store separation): the M16-E boundary's real signature is
 *   bool GenerateMaterialSlotMaskInstanceResult(const FVertexMaskForgeMaskInstance&,
 *       FVertexMaskForgeWorkingMesh& WorkingMesh, bool bUseSourceTopology, const FStaticMeshLODResources*)
 * -- it takes a single, non-const FVertexMaskForgeWorkingMesh&, reads Material Slot's geometry/lookup
 * fields directly off it (RenderVertexToMaterialSlot, DynamicTriangleToMaterialSlot, MaterialSlotOptions,
 * bMaterialSlotResolutionValid, Mesh), and unconditionally writes its result into THAT SAME WorkingMesh's
 * own WorkingMesh.InstanceResults member -- there is no separate result-store parameter to redirect that
 * write elsewhere. FVertexMaskForgeWorkingMesh's copy constructor/assignment are both explicitly deleted
 * (see VertexMaskForgeWorkingMeshTypes.h), so a temporary/staged WorkingMesh duplicate cannot be
 * constructed either. Domain (the geometry/lookup fields) and result store (InstanceResults) are
 * therefore INSEPARABLE in M16-E's real, unmodified contract -- passing WorkingMesh as a single combined
 * parameter is the structurally required exception to "never receive WorkingMesh as a full owner" (see
 * this checkpoint's own audit report for the full reasoning). This module still never chooses WHICH
 * WorkingMesh to use -- the caller supplies it explicitly, exactly like every M16-E test and this
 * module's own tests already do.
 *
 * Atomicity is achieved WITHOUT modifying M16-C or M16-E: FVertexMaskForgeInstanceResultStore (unlike
 * FVertexMaskForgeWorkingMesh) has no deleted copy operations -- it wraps a single TMap and is safely,
 * cheaply copyable. This module snapshots WorkingMesh.InstanceResults (a copy of the "third domain" that
 * module's own doc comment already describes as "substitutable, removable, never authoritative recipe
 * state" -- copying it is not copying an owner) before generating anything; on ANY failure, the snapshot
 * is restored into WorkingMesh.InstanceResults via plain assignment, exactly undoing every live mutation
 * M16-E made during this call, so the caller observes either full success or the store completely
 * unchanged -- never a partial result.
 */

/** Minimal coordination counts -- never Composite, never EffectiveMask, never a copy of resolved
 *  payloads, never a trace. Preserved unmodified by this module on failure (same struct instance the
 *  caller passed in; only assigned to on total success). */
struct FVertexMaskForgeRecipeInstanceGenerationOutput
{
	/** Distinct InstanceIds required by the recipe's enabled Fill Layers (after InstanceId-only
	 *  deduplication -- a GUID referenced N times across the recipe counts once here). */
	int32 NumRequired = 0;

	/** Of NumRequired, how many already had a usable result in WorkingMesh.InstanceResults
	 *  (Contains(InstanceId) == true) and were therefore left untouched, never regenerated. */
	int32 NumReused = 0;

	/** Of NumRequired, how many were actually generated by this call via the M16-E boundary. */
	int32 NumGenerated = 0;
};

namespace VertexMaskForgeRecipeInstanceGeneration
{
	/**
	 * Ensures every keyed instance result required by Recipe's ENABLED Fill Layers exists in
	 * WorkingMesh.InstanceResults, generating only what is actually missing, via the Material Slot M16-E
	 * boundary -- the only generator this checkpoint may execute.
	 *
	 * bUseSourceTopology/LOD0 are forwarded verbatim to GenerateMaterialSlotMaskInstanceResult for every
	 * GUID that needs generating -- same domain-selection contract as M16-E itself (LOD0 required and
	 * non-null only when bUseSourceTopology is false).
	 *
	 * PHASES (strictly in this order -- see this header's own module comment for the full atomicity
	 * contract):
	 *   1. DISCOVERY: walk Recipe.FillLayers in authoring order; layers with bEnabled==false are skipped
	 *      ENTIRELY -- no lookup, no validation, no inspection of their Mask Instances' GeneratorType or
	 *      Params, no possibility of failing because of their content. For each Mask Instance in an
	 *      enabled layer's MaskStack, in authoring order: its InstanceId must be valid
	 *      (FGuid::IsValid()), or the whole call fails immediately, before any generation. Identity is
	 *      exclusively InstanceId -- GeneratorType, Params, BlendMode, Opacity, LayerId, and array
	 *      position are never used for lookup or deduplication.
	 *   2. DEDUPLICATION + COLLISION DETECTION: the SAME InstanceId, referenced any number of times
	 *      (within one layer, across different layers, anywhere in the recipe), establishes exactly ONE
	 *      requirement, at its first occurrence's authoring order. Every later occurrence of that same
	 *      InstanceId must agree with the first: same GeneratorType, and -- only when that GeneratorType
	 *      is MaterialSlot, the only case with a real, reliable field-by-field comparison available
	 *      (FVertexMaskForgeMaterialSlotParams has no operator==, so this module compares
	 *      SelectedSlotIndex/bInvert directly; no serialization or reflection is introduced for this) --
	 *      the same SelectedSlotIndex/bInvert. Any divergence fails the whole call deterministically,
	 *      before any generator runs.
	 *   3. CLASSIFICATION (still read-only against WorkingMesh.InstanceResults): each distinct requirement
	 *      is classified as ALREADY SATISFIED (WorkingMesh.InstanceResults.Contains(InstanceId) == true --
	 *      reused verbatim, never regenerated, regardless of which generator originally produced it: the
	 *      store's own contract is generator-agnostic, presence alone proves usability -- see
	 *      VertexMaskForgeInstanceResultStore.h's own module comment), TO GENERATE (GeneratorType ==
	 *      MaterialSlot and no existing entry), or UNSUPPORTED (any other GeneratorType and no existing
	 *      entry). If ANY requirement classifies as UNSUPPORTED, the whole call fails HERE -- before the
	 *      first generator call -- even if every other requirement (including ones appearing earlier in
	 *      the recipe) would have generated successfully.
	 *   4. GENERATION: only reached if every requirement classified successfully. WorkingMesh.InstanceResults
	 *      is snapshotted first. Requirements classified TO GENERATE are then generated, in their
	 *      first-occurrence discovery order, via GenerateMaterialSlotMaskInstanceResult against the real
	 *      WorkingMesh (there is no separate staging store -- see this header's own module comment for
	 *      why). The FIRST occurrence's FVertexMaskForgeMaskInstance is used for generation (Params/
	 *      GeneratorType already proven identical to every other occurrence of the same InstanceId in
	 *      step 2). On the first generation failure, WorkingMesh.InstanceResults is restored from the
	 *      snapshot (undoing every successful generation already made during this call) and the whole
	 *      call fails -- no partial publication, ever.
	 *   5. SUCCESS: OutResult is only assigned after every requirement is satisfied (reused or generated).
	 *
	 * Recipe empty, or containing only disabled Fill Layers, or containing only enabled Fill Layers with
	 * empty Mask Stacks: zero requirements discovered, zero store lookups, zero generation, immediate
	 * success -- OutResult.NumRequired/NumReused/NumGenerated are all 0, WorkingMesh.InstanceResults is
	 * left completely untouched (not even snapshotted, since there is nothing to roll back).
	 *
	 * Never validates non-finite (NaN/Inf) values anywhere -- Material Slot's own real parameters
	 * (SelectedSlotIndex: int32, bInvert: bool) have no floating-point fields to begin with, and this
	 * module adds no sanitization beyond what GenerateMaterialSlotMaskInstanceResult itself already does.
	 */
	bool GenerateRequiredInstanceResultsForRecipe(
		const FVertexMaskForgeRecipe& Recipe,
		FVertexMaskForgeWorkingMesh& WorkingMesh,
		bool bUseSourceTopology,
		const FStaticMeshLODResources* LOD0,
		FVertexMaskForgeRecipeInstanceGenerationOutput& OutResult);
}
